### PR TITLE
Initial creation of script to run and test all functions.

### PR DESCRIPTION
**Pull request by Lextuga007**
New script to help run all code together to test speeds.

### CODE REVIEW

**Comment by r-ash** [comment]
I wonder if we can move this into a `scripts` directory? Otherwise this will be run on package load.

**Comment by Lextuga007** [comment]
Yes, good idea. Thanks

**Comment by Lextuga007** [comment]
I've deleted the file from the main R folder and amended it in the Scripts folder.

**Review by r-ash — APPROVED** [review]
Perfect!

**Pull request merged**
